FishingStoreApp/Areas/Admin/Controllers/PromotionController.cs
using FishingStoreApp.DataAccess.Data;
using FishingStoreApp.DataAccess.Repository.IRepository;
using FishingStoreApp.Models;
using FishingStoreApp.Models.ViewModels;
using FishingStoreApp.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace FishingStoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.AdminRole)]
    public class PromotionController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PromotionController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Promotion> objPromoList = _unitOfWork.Promotion.GetAll().ToList();
            return View(objPromoList);
        }

        public IActionResult Upsert(int? id)
        {
            Promotion objPromoList = new Promotion();

            if (id == null || id == 0)
            {
                return View(objPromoList);
            }
            else
            {
                //update
                objPromoList = _unitOfWork.Promotion.Get(u=>u.Id == id);
                return View(objPromoList);
            }
        }

        [HttpPost]
        public IActionResult Upsert(Promotion obj)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if(obj.Id == 0)
                    {
                        _unitOfWork.Promotion.Add(obj);
                    }
                    else
                    {
                        _unitOfWork.Promotion.Update(obj);
                    }

                    _unitOfWork.Save();
                    TempData["success"] = "Promo created successfully.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                
                throw new Exception("An error occurred when updating the database", ex);
            }

            return View(obj);
        }

        #region
        [HttpGet]
        public IActionResult GetAll()
        {
            List<Promotion> objPromoList = _unitOfWork.Promotion.GetAll().ToList();
            return Json(new { data = objPromoList });
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var promoToBeDeleted = _unitOfWork.Promotion.Get(u=>u.Id==id);

            if(promoToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Promotion.Remove(promoToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Promo deleted successfully" });
        }


        #endregion
    }
}

FishingStoreApp/Areas/Admin/Views/Promotion/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model List<Promotion>
<div class="card shadow border-0 my-4" style="border-radius: 15px">
    <div class="card-header bg-primary ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-light py-2">Promo List</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="Promotion" asp-action="Upsert" class="btn btn-primary" style="border-radius:10px"><i class="bi bi-plus-circle"></i> Add Promo</a>
            </div>
        </div>

        <table id="tblData" class="table table-bordered table-striped" width="100%">
            <thead>
                <tr>
                    <th>Promotion Name</th>
                    <th>Discount</th>
                    <th>Expiry Date</th>
                    <th>Active</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts {
    <script src="~/js/promotion.js"></script>
}

FishingStoreApp/Areas/Admin/Views/Promotion/Upsert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Promotion
<div class="card shadow border-0 my-4" style="border-radius: 15px;">
    <div class="card-header bg-primary ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-light">@(Model.Id != 0 ? "Update" : "Create") Promo</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form method="post" class="row">
            <input hidden asp-for="Id" />
            <a asp-controller="Promotion" asp-action="Index" class="text-body-emphasis" style="width:150px; text-decoration:none; margin-bottom:15px"><i class="bi bi-arrow-return-left"></i> Back</a>
            <div class="row">
                <div class="col-10">
                    <div class="border p-3" style="border-radius: 5px">
                        <div class="mb-3 p-1 py-2 col-12">
                            <label asp-for="PromoName" class="ms-2"></label>
                            <input asp-for="PromoName" class="form-control border-0 shadow" />
                            <span asp-validation-for="PromoName" class="text-danger"></span>
                        </div>
                        <div class="mb-3 p-1 py-2 col-12">
                            <label asp-for="Discount" class="ms-2"></label>
                            <input asp-for="Discount" class="form-control border-0"/>
                            <span asp-validation-for="Discount" class="text-danger"></span>
                            
                        </div>
                        <div class="mb-3 p-1 py-2 col-12">
                            <label asp-for="ExpiryDate" class="ms-2"></label>
                            <input asp-for="ExpiryDate" id="ExpiryDate" class="form-control border-0 shadow" />
                            <span asp-validation-for="ExpiryDate" class="text-danger"></span>
                        </div>
                        <div class="mb-3 p-1 py-2 col-3">
                            <label asp-for="IsActive" class="ms-2"></label>
                            <input asp-for="IsActive" type="checkbox" />
                            <span asp-validation-for="IsActive" class="text-danger"></span>
                        </div> 

                        <div class="row mt-3">
                            <div class="col-6">
                                @if (Model.Id != 0)
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px; border-radius:10px;">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary" style="width:150px; border-radius:10px;">Create</button>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }

}